syntax on
set number
set nowrap
set tabstop=4
set shiftwidth=4
set hlsearch
set nomodeline
colorscheme peachpuff
hi MatchParen ctermfg=red ctermbg=NONE
hi Search term=reverse ctermfg=0 ctermbg=3 guibg=Gold2

" Map ctrl-/ in command mode to clear search state (unhighlight search items)
map  :let @/ = ""<CR>
command Git /^[<>|=]\{7\}

" Expand tabs except for these projects / under these directories:
:autocmd BufRead,BufNewFile ~/src/* set expandtab
:autocmd BufRead,BufNewFile ~/src/awp/* set noexpandtab
:autocmd BufRead,BufNewFile ~/src/girc/* set noexpandtab
:autocmd BufRead,BufNewFile ~/src/microlibs/* set noexpandtab
:autocmd BufRead,BufNewFile ~/src/mikeirc/* set noexpandtab
:autocmd BufRead,BufNewFile ~/src/pylibs/* set noexpandtab
:autocmd BufRead,BufNewFile ~/src/scripts/* set noexpandtab

" Settings for yaml files
:autocmd BufRead,BufNewFile *.yaml set expandtab ts=2 sw=2
:autocmd BufRead,BufNewFile *.yml set expandtab ts=2 sw=2
:autocmd BufRead,BufNewFile *.*sonnet set expandtab ts=2 sw=2
