syntax on
set number
set nowrap
set tabstop=4
set shiftwidth=4
set hlsearch
set nomodeline
hi MatchParen ctermfg=red ctermbg=NONE

" Map ctrl-/ in command mode to clear search state (unhighlight search items)
map  :let @/ = ""<CR>

" Expand tabs only for these projects / under these directories:
:autocmd BufRead,BufNewFile ~/cs/* set expandtab
