syntax on
set number
set nowrap
set tabstop=4
set shiftwidth=4
set hlsearch
set nomodeline
hi MatchParen ctermfg=red ctermbg=NONE

" Map ctrl-/ in command mode to clear search state (unhighlight search items)
map  :let @/ = ""<CR>

" Expand tabs only for these projects / under these directories:
:autocmd BufRead,BufNewFile ~/src/boltons/* set expandtab

" set noeol for this one project that doesn't like trailing newlines
:autocmd BufRead,BufNewFile ~/src/txircd/* set noeol expandtab

" Settings for yaml files
:autocmd BufRead,BufNewFile *.yaml set expandtab ts=2 sw=2
