
PATH="/home/mike/bin:$PATH"

# Set cursor
xsetroot -cursor_name left_ptr

# Unclutter hides the cursor when idle
unclutter &

# Load custom keymap (my one sets CAPSLOCK->ESC)
[ -f ~/.Xkeymap ] && xkbcomp ~/.Xkeymap $DISPLAY

# Disable monitor powersaving and screensaver
#setterm -blank 0 -powersave off -powerdown 0
# TODO this doesn't work
xset s noblank
xset s off

# xrandr your way into the correct setup
setup-screens

if [ -n "$XRUN" ]; then

	# Special case: run a given command

	[ -n "$XRUN_SINGLE_MONITOR" ] && single-monitor simple

	eval $XRUN
	exit

else

	# This branch is run for main X session only

	# Something stupid is setting my volume wrong on boot, fix it to 100% Master/55% PCM
	setvol

	# log to file
	exec >"$HOME/.xmonad/xmonad.log" 2>&1

	# Startup applications
	terminator &
	chromium &

	# Start up steam in background (still needs an X connection,
	# or we could put this in systemd instead)
	steam -silent -console &

	# Start oculusd (needs an X connection)
	~/src/ovr_sdk_linux_0.4.3/oculusd >~/.oculusd.log 2>&1 &

	exec xmonad

fi
