#!/usr/bin/python2

import json
import os
import sys

PATHS_BY_VALUE = {
	"uploader_id": {
		"FamilyJules7X": "~/music/Artists/FamilyJules7X",
		"MonstercatMedia": "~/music/Artists/Monstercat",
		"pellekofficial": "~/music/Artists/Pellek",
		"SmoothMcGroove": "~/music/Artists/Smooth McGroove",
		"ScottBradleeLovesYa": "~/music/Artists/Post Modern Jukebox",
	}
}

UPLOADER_MAP = '/home/mike/.youtube-dl-music-autopath-uploader-map'
PATHS_BY_VALUE.setdefault('uploader_id', {}).update(
	dict(line.split('\t', 1) for line in open(UPLOADER_MAP).read().strip().split('\n'))
)

def main(video):
	for key, lut in PATHS_BY_VALUE.items():
		if key in video and video[key] in lut:
			return lut[video[key]]

if __name__ == '__main__':
	video = json.loads(sys.stdin.read())
	output = main(video)
	if output:
		print os.path.expanduser(output)
