#!/usr/bin/python2

import sys
from awp.playlist import *

USAGE = ("USAGE: {} {{PLAYLIST}}\n"
         "Merge playlists together by the following rules:\n"
         "Take the weight furthest removed from 16.0\n"
         "Take the volume furthest removed from 0.5\n"
         "All entries are included, even if only present in one playlist"
        ).format(sys.argv[0])

def extreme_by_path(path, *values):
	midpoint = 8 if any(path.startswith(prefix) for prefix in [
		"/home/mike/music/Artists/SilvaGunner/",
		"/home/mike/music/Artists/8 Bit Universe/",
	]) else 16
	return MergeStrategies.extreme(midpoint)(path, *values)

def main(*args):
	if not args:
		sys.stderr.write(USAGE + '\n')
		return 1

	playlists = [Playlist(path) for path in args]
	p1 = playlists.pop(0)
	for p in playlists:
		p1.merge(p, (extreme_by_path, MergeStrategies.extreme(0.5)))
	p1.write(sys.stdout)

if __name__ == '__main__':
	sys.exit(main(*sys.argv[1:]))
