#!/usr/bin/python3

import math
import os
import subprocess

import argh

PATH = '/sys/class/backlight/intel_backlight'

def read(name):
	with open(os.path.join(PATH, name)) as f:
		return int(f.read())

def write(name, value):
	path = os.path.join(PATH, name)
	data = f"{value}\n".encode()
	try:
		with open(path, 'wb') as f:
			f.write(data)
	except PermissionError:
		print(f"Got EACCES on write to {path}, using sudo")
		# We are invoking sh in the form: sh -c COMMAND $0 $1
		# This prevents any issues (however unlikely) with special chars in path.
		subprocess.run(["sudo", "sh", "-c", 'cat > "$1"', "-", path], input=data)

@argh.arg('percent', nargs='?', default=None, metavar='PERCENT|#VALUE|min|max')
def main(percent):
	"""Set or get backlight brightness.
	Give a percentage to set, or #N to set to an explicit integer N.
	Give no args to query.
	"""
	if percent == 'min':
		percent = '#1'
	if percent == 'max':
		percent = '100'
	if percent and percent.startswith('#'):
		write('brightness', int(percent[1:]))
		return
	maxval = read('max_brightness')
	if percent is None:
		value = read('brightness')
		print("{:.2f}% ({}/{})".format(100. * value / maxval, value, maxval))
	else:
		percent = float(percent)
		value = int(math.ceil(maxval * percent / 100.))
		write('brightness', value)

if __name__ == '__main__':
	argh.dispatch_command(main)
