#!/bin/env python

def get_info(key):
	with open("/sys/class/power_supply/BAT0/" + key) as f:
		return int(f.read().strip())

charge = get_info('charge_now')
design = get_info('charge_full_design')
last_full = get_info('charge_full')

print 'Absolute Charge: %.2f%%' % (100.0*charge/design)
print 'Relative Charge: %.2f%%' % (100.0*charge/last_full)
print 'Battery Health:  %.2f%%' % (100.0*last_full/design)

