#!/bin/env python

import os

def get_info(key):
	batteries = [x for x in os.listdir("/sys/class/power_supply/") if x.startswith('BAT')]
	if len(batteries) > 1:
		print "Warning: Multiple batteries detected. Using first."
	battery = batteries[0]
	with open("/sys/class/power_supply/{}/{}".format(battery, key)) as f:
		return int(f.read().strip())

charge = get_info('energy_now')
design = get_info('energy_full_design')
last_full = get_info('energy_full')

print 'Absolute Charge: %.2f%%' % (100.0*charge/design)
print 'Relative Charge: %.2f%%' % (100.0*charge/last_full)
print 'Battery Health:  %.2f%%' % (100.0*last_full/design)

