#!/bin/bash

ENV="${1:?Need an environment, eg local}"

PIDS=()
trap 'kill "${PIDS[@]}"' exit

run() {
	"$@" &
	PIDS+=("$!")
}

run ~/src/service-conf/connect "$ENV"
run chrome-with-pac 'http://localhost:8080/proxy.pac'

# wait for either
wait -n
