#!/bin/bash

USAGE="$0 [FORMAT]"
[ "$1" == "--help" ] && { echo "$USAGE" >&2; exit 255; }

FORMAT="${1:-%T}"
BANNER="${BANNER:-banner}"

while sleep 1; do
	clear
	echo
	$BANNER "$(date "+$FORMAT")"
done
