#!/bin/bash

set -e

USAGE="$0 NAME ROMFILE
Waits until an SD card is inserted, then copies the rom to it
under the name NAME-EPOCH"

if [ "$#" -ne 2 ]; then
	echo "$USAGE" >&2
	exit 255
fi

NAME=$1
ROMFILE=$2

echo "Waiting for sdcard..."
while ! sudo mount /mnt/sdcard; do sleep 1; done
echo "Copying"
rm -f /mnt/sdcard/"$NAME"-*.gb
cp "$ROMFILE" "/mnt/sdcard/$NAME-$(date +%s).gb"
sudo umount /mnt/sdcard
echo Done
