#!/bin/env python2

import re
import logging
from random import SystemRandom

import argh


def main(n=1, words='/usr/share/dict/cracklib-small'):
	"""Generate a 'correct horse battery staple'-style password using /dev/urandom"""
	logging.basicConfig(level=logging.INFO)
	rng = SystemRandom()
	with open(words) as f:
		wordlist = [
			word
			for word in f.read().strip().split('\n')
			if re.match(r'^\w+$', word) and word == word.lower()
		]
	logging.info("Picking from {} words".format(len(wordlist)))
	for _ in xrange(n):
		print " ".join(rng.choice(wordlist) for _ in range(4))


if __name__ == '__main__':
	argh.dispatch_command(main)
