#!/bin/bash

USAGE="$0 TIMESPEC [COMMAND {ARGS}]
Do a banner-style countdown starting from TIMESPEC.
TIMESPEC should be either integer seconds, or in one of the forms:
	XXm XXmXX XXmXXs XX:XX
For example: 10m, 10m00, 10m0s, 10:00 or 600 are all ways of saying 10 minutes.
If given, COMMAND will be run with ARGS once the timer has completed.
"

now() {
	date +%s
}

timestr=$1
BANNER="${BANNER:-banner}"
shift
if egrep -q '^[0-9]+[m:][0-9]*s?$' <<<"$timestr"; then
	# of form XXm, XXmXXs? or XX:XXs?, eg. 10m, 10m30s, 10m30, 10:30
	leading_number () { grep -o '^[0-9]*' <<<"$1"; }
	mins=`leading_number "$timestr"`
	secs=`leading_number $(egrep -o '[0-9]*s?$' <<<"$timestr")`
	duration=$((mins*60+secs))
	unset leading_number
else
	duration="$timestr"
fi

start=$(now)
diff=1
while (( diff > 0 )); do
	diff=$(( duration - ($(now) - start) ))
	m=$((diff/60))
	s=$((diff-m*60))
	clear
	echo
	$BANNER "`printf "%02d:%02d" "$m" "$s"`"
	sleep 1
done
clear

[ "$#" -gt 0 ] && "$@"
