#!/bin/bash

if [ "$#" -lt 1 ]; then
	echo "USAGE: $0 COMMAND {ARGS}" >&2
	echo "Run COMMAND with the depict virtualenv sourced" >&2
fi

source ~/src/depict/.env/bin/activate
export DEPICT_ROOT="/home/mike/src/depict"
export DEPICT_DATA_PATH="/home/mike/random/scratch/depict_data"
exec "$@"
