#!/bin/bash

# These subscriptions are created dynamically, but Vanta complains if they don't have an ownership label.
# Changing the creation code was difficult and risky, so instead we just periodically run this to add labels to them.
gcloud --format json --project depict-ai-production pubsub subscriptions list |
	jq -r '.[]|select(.labels["vanta-owner"] == null)|.name' |
	xargs -r -n1 -P8 gcloud --project depict-ai-production pubsub subscriptions update --update-labels vanta-owner=engineering
