#!/bin/bash

if [ "$#" -lt 1 ]; then
	echo "USAGE: $0 SECRET {GCLOUD_ARGS}" >&2
	echo "Print value of named secret in depict env." >&2
	echo "gcloud args are passed through, allowing eg. a specific project or output format" >&2
	exit 1
fi

SECRET="$1"
shift

gcloud secrets versions access latest --secret "$SECRET" "$@"
