#!/bin/bash

NAME="$HOME/random/design-question-$(date +%F)"
if [ -f "${NAME}.notes" ]; then
	n=1
	while [ -f "$NAME-$n.notes" ]; do
		n=$((n+1))
	done
	NAME="$NAME-$n"
fi
NAME="$NAME.notes"
cp ~/random/design-question.notes "$NAME"
exec vim "$NAME"
