#!/bin/bash

set -eu

if [ "$#" -lt 1 ]; then
	echo "USAGE: $0 [-MODIFIER] DATE" >&2
	echo "Generate a discord timestamp for given time and put it on clipboard" >&2
	echo "Known modifiers:"
	echo "    -R: relative"
	echo "    -t: HH:MM"
	echo "    -T: HH:MM:SS"
	echo "    -d: D/M/Y (probably locale dependent)"
	echo "    -D: Month D, YYYY"
	echo "    -f: Month D, YYYY at HH:MM (default)"
	echo "    -F: Weekday, Month D, YYYY at HH:MM"
	exit 1
fi

MODIFIER=
if grep -q "^-" <<<"$1"; then
	MODIFIER=":${1:1}"
	shift
fi

TIME=$(date -d "$*" +%s)
echo "Time interpreted as: $(date -d"@$TIME" '+%F %T')" >&2
TIMESTR="<t:${TIME}${MODIFIER}>"
echo -n "$TIMESTR" | xclip -selection clipboard
echo "$TIMESTR"
