#!/bin/bash

set -euo pipefail

USAGE="$0 REPO [TAG]
Build current directory then push. Default to git commit for tag."

if [ "$#" -lt 1 ]; then
	echo "$USAGE" >&2
	exit 255
fi

REPO="$1"

if [ "$#" -lt 2 ]; then
	TAG=$(git rev-parse HEAD|head -c 8)
else
	TAG="$2"
fi

docker build . -t "$REPO:$TAG"
docker push "$REPO:$TAG"
