#!/bin/bash

if [ "$#" -lt 1 ]; then
	echo "USAGE: $0 {PATHS}" >&2
	exit 1
fi

for p in "$@"; do
	find "$p" -xdev -type f -exec du -a {} +
done |
	awk -F'\t' '{s = $2; gsub("/", ";", s); print s, $1}' |
	flamegraph.pl
