#!/bin/bash

set -o pipefail

for f in "$@"; do
	[ -f "$f" ] || {
		echo "Not a file: $f"
		continue
	}
	if ! gofmt -s "$f" | diff -u "$f" -; then
		read -p "Press enter to apply or ^C to abort"
	fi
	gofmt -s -w "$f"
done
