#!/bin/env python

import sys
from subprocess import check_call as cmd
from subprocess import check_output as cmd_out
from subprocess import CalledProcessError

out = cmd_out(['git', 'ls-remote', 'origin'])
refs = [line.split("\t") for line in out.strip().split("\n")]

changes = {}
for commit, ref in refs:
	if '/changes/' not in ref: continue
	change_id = ref.split("/")[3] # refs/changes/??/CHANGE_ID/PATCH_NO
	changes[change_id] = commit

fetch_args = [':'.join([commit, "refs/changes/%s" % change_id]) for change_id, commit in changes.items()]
cmd(['git', 'fetch', '-f', 'origin'] + fetch_args)
