#!/bin/bash

USAGE="$0 REFSPEC [COMMAND {ARGS}]
Checkout given REFSPEC, run a new bash instance, checkout previous head on exit.
If a command is given, run that then exit instead."
subject="${1:?$USAGE}"
shift
current="$(git symbolic-ref HEAD)"
current="${current#refs/heads/}"

changes="$(git status --porcelain --untracked-files=no)"
if [ -n "$changes" ]; then
	git stash || exit
fi

git checkout $subject || exit 1
if [ $# -lt 1 ]; then
	bash
else
	"$@"
fi
ret="$?"
git checkout $current || exit 1

if [ -n "$changes" ]; then
	git stash pop || exit 1
fi

exit "$ret"
