#!/bin/bash

review='/usr/bin/git-review'

flag_in_args() {
	# check for presence of $1 in remaining args
	# returns success if $1 is present.
	flag="$1"
	shift
	for arg in "$@"; do
		[ "$arg" == "$flag" ] && return 0
	done
	return 1
}

OPTS=('-y')

flag_in_args "-r" "$@" || OPTS+=('-r' 'origin')

"$review" "${OPTS[@]}" "$@"
