#!/bin/bash

# Run git rebase, but run prettier on all modified .ts files after each commit,
# creating a (possibly empty) prettier fixup commit.
exec git rebase -x '
	git show --name-only --format= |
		grep \\.ts\$ |
		xargs -d"\n" npx prettier -w
	&& git commit --allow-empty -am "prettier fixup"
' "$@"
