#!/bin/bash

USAGE="$0 (staging|prod|prod-only) [TARGET]
'hotfix' TARGET onto staging or prod according to glide's practices.
If 'prod' is given, hotfixes to both staging and prod. Use 'prod-only' to not hotfix to staging.
TARGET defaults to dev, and may be a range, eg. dev~2..dev"

set -eu

if [ "$#" -eq 0 ]; then
	echo "$USAGE" >&2
	exit 255
fi

BASE="$1"
TARGET="${2:-dev}"

hotfix() {
	git checkout "$1"
	git reset --hard "origin/$1"
	git cherry-pick "$TARGET"
	read -rp "Confirm push this to $1? [y/N] > " resp
	[ "$resp" == "y" ]
	PUSH_MASTER=true git push origin "$1"
}

git fetch origin
case "$BASE" in
	staging)
		hotfix staging
		;;
	prod)
		hotfix staging
		hotfix prod
		;;
	prod-only)
		hotfix prod
		;;
	*)
		echo "Invalid base: $BASE" >&2
		echo >&2
		echo "$USAGE" >&2
		exit 255
		;;
esac
