#!/bin/bash

USAGE="$0 SUBJECT [TARGET]
Fast-forward SUBJECT branch to TARGET ref (default HEAD) and push."


subject="${1:?$USAGE}"
current="$(git symbolic-ref HEAD | cut -d/ -f3)"
target="${2:-$current}"

git checkout $subject && git merge --ff-only $target && git push
git checkout $current
