#!/bin/bash

git remote -v | grep origin | awk '$3 == "(fetch)" {print $2}' | awk -v"GOPATH=$GOPATH" -F: '{host=$1; if (host == "github") host="github.com"; printf "%s/src/%s/%s\n", GOPATH, host, $2}'
