#!/bin/bash

USAGE="$0 JQ_PROG [LIVETAIL_ARGS]
Run loggly livetail, convert logs to json form with livetail-to-json, then run them through given jq program.
Optional livetail args can be used to tune livetail, but by default we match everything (-m .*).
"

if [ "$#" -lt 1 ]; then
	echo "$USAGE" >&2
	exit 255
fi

JQ_PROG="$1"
shift 1

if [ "$#" -lt 1 ]; then
	LIVETAIL_ARGS=('-m' '.*')
else
	LIVETAIL_ARGS=("$@")
fi

livetail "${LIVETAIL_ARGS[@]}" | livetail-to-json | jq "$JQ_PROG"
