#!/bin/bash

trap 'echo -e "\x1b[m"' exit
sed -s '
	s/\(.*\)DEBUG/\x1b[0;35m\1DEBUG/;
	s/\(.*\)INFO/\x1b[32;1m\1INFO/;
	s/\(.*\)WARNING/\x1b[0;33m\1WARNING/;
	s/\(.*\)ERROR/\x1b[31;1m\1ERROR/;
	s/\(.*\)CRITICAL/\x1b[30;41;1m\1CRITICAL/;
'
