#!/bin/bash

OLD_VOL=$(
    amixer -M -c 0 get PCM |
    egrep '^  Front Left:' |
    egrep -o '[0-9.]*%'
)

if ! [ -n "$OLD_VOL" ]; then
    echo "Could not determine current volume" >&2
    exit 1
fi

amixer -qMc 0 set PCM 100%
read -p "Press any key to return volume to $OLD_VOL
" -s -n1
amixer -qMc 0 set PCM "$OLD_VOL"

