#!/bin/bash

OLD_VOL=$(
	amixer -M get PCM |
	egrep '^  Front Left:' |
	egrep -o '[0-9.]*%'
)

if ! [ -n "$OLD_VOL" ]; then
	echo "Could not determine current volume" >&2
	exit 1
fi

NEW_VOL="${1:-100}"

amixer -qM set PCM "$NEW_VOL%"
read -p "Press any key to return volume to $OLD_VOL
" -s -n1
amixer -qM set PCM "$OLD_VOL"

