#!/bin/bash

OLD_VOL=$(
	amixer -M get Master |
	grep -E '^  (Front Left|Mono):' |
	grep -Eo '[0-9.]*%'
)

if ! [ -n "$OLD_VOL" ]; then
	echo "Could not determine current volume" >&2
	exit 1
fi

NEW_VOL="${1:-100}"
shift

amixer -qM set Master "$NEW_VOL%"

if [ "$#" -lt 1 ]; then
	read -p "Press any key to return volume to $OLD_VOL
" -s -n1
else
	"$@"
fi

amixer -qM set Master "$OLD_VOL"

