#!/bin/awk -f

# Count of counts of unique inputs
# ie. how many inputs were unique, how many had 2 instances, how many had 3 instances, etc.

{
	c[$0] += 1;
}

END {
	for (k in c) {
		cc[c[k]] += 1
	}
	printf "%s\t%s\n", "META", "COUNT";
	for (count in cc) {
		printf "%d\t%d\n", cc[count], count;
	}
}
