#!/bin/bash

set -e

minikube stop </dev/null || true
minikube delete || true

minikube start --cpus=$(nproc) --memory=16384 --host-only-cidr=192.168.97.1/26 --disk-size=100G

minikube-sync
kubectl config use-context minikube
kubectl apply -f <(find ~/src/service-conf/k8s/local -name '*-ns.yaml' -exec cat {} +)
kubectl apply -f <(find ~/src/service-conf/k8s/local -name '*.yaml' -exec cat {} +)
