#!/bin/bash

export INTERVAL=${INTERVAL:-60}

exec 2>/dev/null

(while sleep "$INTERVAL"; do
	eval $(xdotool getmouselocation --shell)
	RAND=$((RANDOM % 8))
	swarp $((X+RAND-4)) $Y
done) &
pid="$!"

echo -n "Press any key to exit"
read -n1
kill $pid && wait $pid
echo
