#!/bin/bash

export INTERVAL=${INTERVAL:-60}

exec 2>/dev/null

(while sleep "$INTERVAL"; do
	RAND=$((RANDOM % 8))
	xdotool mousemove_relative $((RAND-4)) 0
done) &
pid="$!"

echo -n "Press any key to exit"
read -n1
kill $pid && wait $pid
echo
