#!/bin/bash

USAGE="$0 {FILE}\nPrint the duration of each input audio file"

if [ "$#" -lt 1 ]; then
	echo -e "$USAGE" >&2
	exit 1
fi

for arg in "$@"; do
	ffprobe -of json -show_entries streams "$arg" 2>/dev/null | jq -r --arg name "$arg" '
		.streams[] |
		select(.codec_type == "audio") |
		.duration |
		tonumber |
		[.,
		 ([(. / 60 | floor), . % 60] | map(tostring) | join(":")),
		 $name] |
		map(tostring) |
		join("\t")
	'
done
