#!/bin/bash

# start folding since we're not being used otherwise
fahctl unpause

(
	# wait for user to step away, then off screens
	sleep 5
	xset dpms force off

	# re-off screens regularly in case the mouse moves accidentially
	while sleep 15; do
		xset dpms force off
	done
) &
pid="$!"

trap 'kill "$pid"; fahctl pause; echo' exit
read -s -N1 -p'Press any key to exit '
