#!/bin/bash

# NOTE: This script is intended to be called by udev, and so should not start any long-term procs.
# Be aware that it will run as root.

USAGE="
`basename $0` DEV [PATH]

This script will mount a device and fill it with music
taken from an awp playlist.
Args are as follows:
	DEV: Path to device to mount
	PATH: Path within the mounted fs to place files. Default \"MUSIC\".
"

PLAYLIST="${PLAYLIST:-/home/mike/main.awp}"
MIN_REMAINING="$((1024 * 1024))" # 1MiB
LOGFILE="/var/log/usb-populate.log"
LOCKFILE="/var/lock/usb-populate"
LOCK_TIMEOUT=5
MOUNT_ARGS="-t vfat"
BANNER=${BANNER:-banner}
# NO_DELETE: set to preserve existing contents

locked=''

cleanup() {
	[ -n "$locked" ] && flock -u 99
	if [ -d "$MOUNTPOINT" ]; then
		umount "$MOUNTPOINT"
		rmdir "$MOUNTPOINT"
	fi
}

log() {
	echo "$@" >>"$LOGFILE"
	[ -n "$DEBUG" ] && echo "$@" >&2
}

die() {
	cleanup
	local code="$1"
	shift
	log "$@"
	exit "$code"
}

report_progress() {
	[ -n "$DEBUG" ] || clear
	$BANNER "$(df --output=pcent "$DEV" | tail -n+2)"
}

[ $# -lt 1 ] && die 255 "$USAGE"

log "$0" "$@"

DEV="$1"
TARGET="${2:-MUSIC}"
shift 2

# udev sometimes runs multiple copies (?)
# to avoid contention for who gets to mount, we simply try to flock or exit.
exec 99>"$LOCKFILE" || die 1 "Cannot open lockfile"
flock -w "$LOCK_TIMEOUT" 99 || die 1 "Cannot acquire lock"
locked=true

MOUNTPOINT="$(mktemp -p /mnt -d)"
[ -n "$MOUNTPOINT" ] || die 1 "Failed to create temporary mount point"

mount "$DEV" "$MOUNTPOINT" $MOUNT_ARGS || die 2 "Failed to mount"

# clear old files first
[ -n "$NO_DELETE" ] || rm "$MOUNTPOINT/$TARGET/"*

get_remaining() {
	sync
	local ret="$(df --output=avail -B 1 "$DEV" | tail -n+2)"
	[ -n "$ret" ] || die 3 "Failed to get df output"
	echo "$ret"
}
log "Populating $DEV with $(get_remaining) bytes"

python -m awp.generate "$PLAYLIST" |
for ((n=0; 1; n++)); do
	[ -n "$converted" ] && rm -f "$converted"
	converted=
	read file
	log "Considering $file"
	[ -f "$file" ] || { log "file does not exist: $file"; continue; }
	filebase="$(basename "$file")"
	if ! grep -q '\.mp3$' <<<"$file"; then
		oldfile="$file"
		file="/tmp/$RANDOM-${filebase%.*}.mp3"
		converted="$file"
		ffmpeg -i "$oldfile" "$file" </dev/null >/dev/null 2>&1 || continue
	fi
	filesize="$(stat -c %s "$file")"
	[ -n "$filesize" ] || { log "failed to get size of: $file"; continue; }
	remaining="$(get_remaining)"
	newremaining="$((remaining - filesize))"
	log "File size: $filesize  Remaining space: $remaining"
	[ "$newremaining" -gt "$MIN_REMAINING" ] || break
	filenum="$(printf "%04d" "$n")"
	cp "$file" "$MOUNTPOINT/$TARGET/$filenum-$filebase" || continue
	log "Copied $MOUNTPOINT/$TARGET/$filenum-$filebase"
	report_progress
done
[ -n "$converted" ] && rm -f "$converted"
log "Disk is full. Complete"

cleanup
