#!/usr/bin/env python3
 
from importlib import import_module
from sys import argv, exit
import os
 
args = list(argv[1:])

dir = False
if args and args[0] == '--dir':
	args = args[1:]
	dir = True

if not args:
	print('USAGE: {0} [--dir] MODULE\nPrint filepath of module, or containing directory if --dir'.format(*argv))
	exit(1)
 
module = args[0]
subject = import_module(module)

orig_path = subject.__file__
path, ext = os.path.splitext(orig_path)
py_path = path + '.py'
if os.path.exists(py_path):
	if dir:
		py_path = os.path.dirname(py_path)
	print(py_path)
else:
	print(orig_path)
