#!/bin/bash

result=$(zbarimg -q -Sdisable -Sqrcode.enable "$@")
if ! grep -q "^QR-Code:" <<<"$result"; then
	echo "Unexpected output, did not start with 'QR-Code:': $result" >&2
	exit 1
fi
sed 's/^QR-Code://' <<<"$result"
