#!/usr/bin/env python

def main(role, *range_args):
	range_args = map(int, range_args)
	print ','.join(role.format(x) for x in range(*range_args))

if __name__ == '__main__':
	import sys
	main(*sys.argv[1:])
