#!/bin/bash

cd ~/analytics
export MP_ENV_TYPE=live
source ~/env/bin/activate

BUF="$(tempfile)"

tail -f "$BUF" &
pid="$!"
trap 'rm "$BUF"; kill "$pid"' exit

python -u "$(which fab)" "$@" >>$BUF 2>&1
