#!/bin/bash
# selectFiles runs through each file or folder, offering option yes, no or recurse (run for inside the folder)
# NOTE: Will fail if filepaths contain '\' (which they shouldn't)

output=$1
if [ ! "$output" ]; then
	output="/dev/stdout"
fi

fileloop () {
	local line formattedline
	# $1: target directory

	OLDIFS="$IFS"
	IFS="
"
	for line in $(ls "$1" -B1); do
		IFS="$OLDIFS"
		ask "$1/$line"
	done
}

ask () {
	# $1: target file/directory
	if [ -d "$1" ]; then
		echo -n "$1 (y/n/r) > " >&2
		read -n 1 answer #reads one character
		echo >&2
		case "$answer" in
		r)
			fileloop "$1" ;;
		y)
			echo "$1">>$output ;;
		n)
			;;
		*)
			echo "Unrecognised response." >&2
			ask "$1" ;;
		esac
	else
		echo -n "$1 (y/n) >" >&2
		read -n 1 answer #reads one character
		echo >&2
		case "$answer" in
		y)
			echo "$1">>$output ;;
		n)
			;;
		*)
			echo "Unrecognised response." >&2
			ask "$1"
		esac
	fi
}

fileloop "$(pwd)"
