#!/bin/bash

xrandr --output eDP2 --mode 1920x1080
	for screen in DP1 DP2 HDMI1 HDMI2 VGA1 VIRTUAL1; do
		xrandr --output "$screen" --off
	done
if [ -z "$X_ONE_SCREEN" ]; then
	xrandr --output DP2-3 --mode 2048x1152 --pos 1920x0 || true # may fail if not connected
fi
