#!/bin/bash

main='DVI-D-0'
right='DP-4'
left='DP-2'
top='DP-0'

xrandr --output "$right" --off
xrandr --output "$top" --off
xrandr --output "$main" --off

xrandr --output "$left" --mode 1920x1080 --pos 0x0
xrandr --output "$main" --mode 1920x1080 --pos 1920x0
xrandr --output "$right" --mode 1920x1080 --rotate left --pos 3840x0
xrandr --output "$left" --mode 1920x1080 --pos 0x420
xrandr --output "$main" --mode 1920x1080 --pos 1920x420
xrandr --output "$top" --mode 1920x1080 --pos 960x-660
