#!/bin/bash

set -e

PLAYLISTS=(
	# FILEPATH NAME SCALE {FILTER}
	"$HOME/main.awp list-64 64"
	"$HOME/main.awp list-32 32"
	"$HOME/main.awp list-64u 64 uniq"
	"$HOME/main.awp list-128u 128 uniq"
	"$HOME/music/playlists/soft.awp soft-32 32"
)

WHITELIST=(
	'Artists/Neil Cicierega/Mouth Sounds'
	'Artists/Neil Cicierega/Mouth Silence'
	'Artists/Neil Cicierega/Mouth Moods'
	'Game Music/Pokemon/Shinesparkers - Harmony of a Champion (Music from Pokémon Red and Green Versions)/'
	'Musicals/Avenue Q Broadway Musical Soundtrack'
	'Musicals/Guys and Dolls'
	'Musicals/Hamilton'
	'Musicals/Jesus Christ Superstar/1996 London Studio Cast/'
	'Musicals/Les Miserables_25th Anniversary Concert_MP3'
	'Musicals/Producers'
	'Musicals/Rocky Horror Picture Show'
	'Musicals/Urinetown - The Musical'
	'Musicals/Wicked_ Original Broadway Cast'
)

# Format note: phone won't recognize .opus files, but they're the same container format as .ogg
# so we create .ogg files that use the opus codec explicitly.
(
	awk -F'\t' '$1 >= 32 {print $3}' ~/main.awp
	awk -F'\t' '$1 >= 32 {print $3}' ~/music/playlists/soft.awp
	for prefix in "${WHITELIST[@]}"; do
		awk -F'\t' -v"prefix=^/home/mike/music/$prefix" '$3 ~ prefix {print $3}' ~/main.awp
	done
) | sort -u |
transcode-cp --stdin --safe --delete --ext=ogg "$@" ~/music/ /srv/phone/music/ -- -vn -b:a 64k -codec:a libopus

for line in "${PLAYLISTS[@]}"; do
	read path name scale filter <<<"$line"
	[ -n "$filter" ] || filter=cat
	python -m awp.to_m3u "$path" ~/music/ . --scale="$scale" |
	$filter | sed 's/\.[^.]\+$/.ogg/' |
	LC_ALL=C sed -e 's|[^a-zA-Z0-9/ .-]|_|g' -e 's|^file_//|file://|' >"/srv/phone/music/$name.m3u"
done
