#!/bin/bash

set -e

PLAYLISTS=(
	# FILEPATH NAME SCALE {FILTER}
#	"playlist 8"
	"$HOME/main.awp list-64 64"
	"$HOME/main.awp list-32 32"
	"$HOME/main.awp list-64u 64 uniq"
	"$HOME/main.awp list-128u 128 uniq"
	"$HOME/main.awp list-16 16"
	"$HOME/music/playlists/soft.awp soft-32 32"
)

awk -F'\t' '$1 >= 16 {print $3}' ~/main.awp |
transcode-cp --stdin --safe ~/music/ /srv/btsync/music/ -- -b:a 64k

for line in "${PLAYLISTS[@]}"; do
	read path name scale filter <<<"$line"
	[ -n "$filter" ] || filter=cat
	python -m awp.to_m3u "$path" ~/music/ . --scale="$scale" |
	$filter | sed 's/\.[^.]\+$/.mp3/' |
	LC_ALL=C sed -e 's|[^a-zA-Z0-9/ .-]|_|g' -e 's|^file_//|file://|' >"/srv/btsync/music/$name.m3u"
done
