#!/bin/bash

TWITCH_USER='ekimekim3000'

_curl() {
	curl "$@" -H 'Client-ID:jzkbprff40iqj646a697cyrvl0zt2m6'
}

fetch_all() {
	endpoint="$1"
	key="$2"
	# fetches endpoint from twitch from successive pages until exhausted
	# and outputs key from endpoint response. exhaused := key is empty
	url="https://api.twitch.tv/kraken/$endpoint?limit=100"
	while true; do
		data=$(_curl -sS "$url")
		[ "$(jq -r ".$key|length" <<<"$data")" -eq 0 ] && break
		jq ".$key[]" <<<"$data"
		url=$(jq -r '._links.next' <<<"$data")
	done
}

if [ -n "$1" ]; then
	CHANNEL="$1"
	shift
fi
if [ -z "$CHANNEL" ]; then
	echo "Getting followed channels"
	# present a list of live followed channels to the user
	follows=$(fetch_all "users/$TWITCH_USER/follows/channels" "follows" | jq -r '.channel.name')
	echo "Following $(wc -l <<<"$follows") channels..."
	live=$(
		for channel in $follows; do
			(
				stream=$(_curl -Ss "https://api.twitch.tv/kraken/streams/$channel" | jq -r '.stream')
				[ "$stream" != "null" ] && echo "$channel"
			)&
		done
		wait
	)
	echo "$(wc -l <<<"$live") channels live"
	echo "Please select a channel below by number, or enter an alternate channel."
	select channel in $live; do
		[ -z "$channel" ] && channel="$REPLY"
		break
	done
	CHANNEL="$channel"
fi
if [ -z "$CHANNEL" ]; then
	echo "No channel given" >&2
	exit 1
fi

exec twitch-irc --channel=#"$CHANNEL" "$@"
