#!/bin/bash

if [ "$1" == "-c" ] | [ "$1" == "--chat-only" ]; then
	CHAT_ONLY=true
	shift
fi

if [ "$#" -lt 1 ]; then
	echo "USAGE: $0 [-c|--chat-only] CHANNEL" >&2
	exit 255
fi

CHANNEL="$(tr A-Z a-z <<<"$1")"

if [ "$1" == "-c" ] || [ "$1" == "--chat-only" ]; then
	shift
	CHAT_ONLY=true
fi

if ! [ -n "$CHAT_ONLY" ]; then
	# Use a sleep process as a waitable signal
	sleep infinity &
	WAITER="$!"

	# setsid prevents ^C in chat from killing video
	setsid twitch-watch "$CHANNEL" | (
		# Copy lines to stdout until we see player starting, then redirect to /dev/null
		while read -r line; do
			echo "$line"
			grep -q "Starting player" <<<"$line" && break
		done
		kill "$WAITER" # wake waiter by killing the process
		cat >/dev/null
	) &
	VIDEO_PID="$!"
	wait "$WAITER"
fi

twitch-irc --channel="#$CHANNEL" "$@"
