#!/bin/bash

if [ "$#" -lt 1 ]; then
	echo "USAGE: $0 ZIPFILE [FILETYPE]" >&2
	exit 255
fi

zip="$1"
ext="${2:-flac}"
name=$(basename "${zip%%.zip}")

set -e
unzip-to-folder "$zip"
[ -d "$name" ] || echo "directory does not exist: $name"
cp ~/main.awp ~/.main.backup.awp
find "$(pwd)/$name" -type f -name "*.$ext" | awp-format >> ~/main.awp
