#!/bin/bash

list() {
	pactl list sink-inputs | awk -F' *[#=] *' '
		$1 == "Sink Input" {s = $2};
		$1 ~ "Volume" {v = substr($1, match($1, "[0-9]+%"), RLENGTH)};
		$1 ~ "application.name" {print s, v, $2}
	'
}

if [ "$#" -eq 0 ]; then
	list
elif [ "$#" -eq 2 ]; then
	pactl set-sink-input-volume "$1" "$2"
else
	echo "USAGE: $0 [INPUT_ID VOLUME]" >&2
	echo "Run without args to get a list of input ids and names" >&2
fi
