#!/bin/bash

USAGE="$0 VIRTUALENV [COMMAND {ARGS}]
Runs bash in virtualenv."

if [ ! "$1" ]; then
	echo "$USAGE"
	exit 1
fi

virtualenv="/var/env/$1"
shift 1

cd "$virtualenv" || exit 1

if [ "$#" -gt 0 ]; then
	bash --rcfile bin/activate -c "$*"
else
	bash --rcfile bin/activate
fi
