#!/bin/env python3

import json
import sys
import yaml

from argh import dispatch_command, arg


@arg('filepaths', help='File to read, or - (default) for stdin', nargs='*', default='-')
def main(filepaths, pretty=True):
	data = []
	for filepath in filepaths:
		if filepath == '-':
			f = sys.stdin
		else:
			f = open(filepath)

		data += list(yaml.safe_load_all(f))
	print(json.dumps(data, indent=4 if pretty else None, default=str))


if __name__ == '__main__':
	dispatch_command(main)
