#!/bin/bash

logexec() {
	echo -e "\e[33m> $@\e[m"
	"$@"
}

PLAYLIST=${PLAYLIST:-~/main.awp}

if [ -n "$DEST" ]; then
	cd "$DEST" || exit 1
else
	cd "$HOME/music" || exit 1

	OLDIFS="$IFS"
	IFS='
	'
	while [ -z "$finished" ]; do
		PS3="Pick a destination in $(pwd) > "
		select dir in $(find -maxdepth 1 -type d | sort); do
			if [ "$dir" == "." ]; then
				finished=true
				break
			fi
			if [ -z "$dir" ]; then
				dir="$REPLY"
				mkdir -p "$dir"
			fi
			cd "$dir" || exit 1
			break
		done || exit 1
	done
	IFS="$OLDIFS"
fi

filepath=$(youtube-dl -x --get-filename "$@")
filepath=${filepath%.*}
ls "${filepath}".* | while read line; do
	echo "DELETING $line"
	rm "$line"
done
logexec youtube-dl -x "$@" || exit 1
filepath=$( ls "${filepath}".* )

# TRIM: format "start:end", where either can be blank
if [ -n "$TRIM" ]; then
	start="${TRIM%%:*}"
	end="${TRIM##*:}"
	newpath="${filepath%.*}.${start}:${end}.${filepath##*.}"
	opts=()
	[ -n "$start" ] && opts+=(-ss "$start")
	[ -n "$end" ] && opts+=(-t "$((end-start))")
	logexec ffmpeg -y "${opts[@]}" -i "$filepath" -strict -2 "$newpath" </dev/null || exit 1
	rm "$filepath"
	filepath="$newpath"
fi

if [ -f "$PLAYLIST" ]; then
	echo -e "16\t0.5\t$(pwd)/$filepath" >> "$PLAYLIST"
	echo "Added to playlist: $PLAYLIST"
fi
